INSERT INTO "promo_codes" (
  "id",
  "code",
  "title",
  "description",
  "type",
  "value",
  "min_order_amount",
  "max_discount_amount",
  "usage_limit",
  "per_user_limit",
  "first_order_only",
  "is_active",
  "updated_at"
) VALUES
  (
    'promo_pizza10',
    'PIZZA10',
    '10% на любую пиццу',
    'Скидка 10% на заказ без минимальной суммы',
    'PERCENT',
    10,
    0,
    1500,
    1000,
    NULL,
    false,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'promo_dodo500',
    'DODO500',
    '500 ₸ от заказа',
    'Скидка 500 ₸ при заказе от 4000 ₸',
    'FIXED_AMOUNT',
    500,
    4000,
    NULL,
    700,
    NULL,
    false,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'promo_first20',
    'FIRST20',
    '20% на первый заказ',
    'Для авторизованных гостей, которые еще не заказывали',
    'PERCENT',
    20,
    3000,
    2500,
    NULL,
    1,
    true,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'promo_bigparty',
    'BIGPARTY',
    'Большая компания',
    '15% при заказе от 8000 ₸',
    'PERCENT',
    15,
    8000,
    4000,
    500,
    NULL,
    false,
    true,
    CURRENT_TIMESTAMP
  ),
  (
    'promo_freeship',
    'FREESHIP',
    'Доставка за наш счет',
    'Минус 600 ₸ от заказа от 3500 ₸',
    'FIXED_AMOUNT',
    600,
    3500,
    NULL,
    800,
    NULL,
    false,
    true,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("code") DO NOTHING;
