CREATE TYPE "STATUS_new" AS ENUM ('NEW', 'PREPARING', 'DELIVERING', 'COMPLETED', 'CANCELED');

ALTER TABLE "orders"
ALTER COLUMN "status" TYPE "STATUS_new"
USING (
  CASE "status"::text
    WHEN 'PENDING' THEN 'NEW'
    WHEN 'SUCCEEDED' THEN 'COMPLETED'
    WHEN 'CANCELED' THEN 'CANCELED'
    ELSE 'NEW'
  END
)::"STATUS_new";

DROP TYPE "STATUS";
ALTER TYPE "STATUS_new" RENAME TO "STATUS";
